const groups = [
  { id:'app', name:'Ứng dụng & URL', note:'Tự đặt — không cần tài khoản dịch vụ', vars:[
    v('NODE_ENV','Chọn chế độ chạy và tối ưu framework.','internal','development','Tự đặt: development ở máy cá nhân, test khi chạy kiểm thử, production khi deploy.','NestJS/Node và thư viện dùng nó để bật tối ưu, giảm log chi tiết và thay hành vi phù hợp môi trường.','const isProd = config.get("NODE_ENV") === "production";','Không dùng NODE_ENV để chứa tên server tùy ý; thường chỉ dùng development, test, production.'),
    v('API_PORT','Cổng backend lắng nghe request.','internal','4000','Tự chọn một cổng chưa bị chương trình khác sử dụng. Docker có thể map cổng ngoài sang cổng này.','main.ts đọc biến và gọi app.listen(port). Frontend phải trỏ API URL tới đúng cổng.','await app.listen(config.get("API_PORT", 4000));','Trong Docker, hostname localhost bên trong container không phải máy host.'),
    v('FRONTEND_URL','Địa chỉ gốc của website người dùng.','internal','http://localhost:3000','Local dùng localhost; production lấy domain frontend sau khi deploy, ví dụ https://book.example.com.','Backend dùng để tạo link email, CORS và URL quay về sau thanh toán.','const resetUrl = `${frontendUrl}/reset-password?token=${token}`;','Không thêm dấu / cuối nếu code tự ghép path.'),
    v('BACKEND_URL','Địa chỉ gốc công khai của API.','internal','http://localhost:4000','Local là địa chỉ NestJS. Production lấy domain API hoặc URL nền tảng deploy.','Dùng tạo webhook/callback, link file proxy và tài liệu API. PayOS phải truy cập được URL production từ Internet.','const webhookUrl = `${backendUrl}/api/v1/payments/payos/webhook`;','localhost không thể nhận webhook từ PayOS nếu không có tunnel.'),
    v('CORS_ORIGINS','Danh sách website được browser phép gọi API.','internal','http://localhost:3000','Liệt kê origin frontend, phân cách dấu phẩy; production dùng chính xác scheme + domain + port.','NestJS so Origin header với danh sách này trước khi trả dữ liệu cho JavaScript trên browser.','app.enableCors({ origin: corsOrigins.split(","), credentials: true });','Không dùng * khi gửi cookie/credential; không thêm path như /login.'),
    v('TZ','Múi giờ mặc định của tiến trình.','internal','Asia/Ho_Chi_Minh','Tự đặt bằng tên IANA. Việt Nam dùng Asia/Ho_Chi_Minh.','Giúp log và lịch nghiệp vụ nhất quán; database vẫn nên lưu timestamp UTC.','process.env.TZ = "Asia/Ho_Chi_Minh";','Không lưu chuỗi giờ địa phương thay cho ISO timestamp/UTC.')
  ]},
  { id:'auth', name:'Xác thực & bảo mật', note:'Secret tự sinh — bắt buộc thay giá trị mẫu', vars:[
    v('JWT_ACCESS_SECRET','Khóa ký access token ngắn hạn.','generated','<random-64-bytes>','Tự sinh bằng trình tạo số ngẫu nhiên mật mã. Không dùng tên dự án, ngày sinh hoặc UUID ngắn.','AuthService ký JWT khi đăng nhập; JwtGuard xác minh chữ ký ở mỗi API riêng tư. Sai secret thì token bị từ chối.','JwtModule.register({ secret: config.getOrThrow("JWT_ACCESS_SECRET") });','Không dùng chung với refresh secret; đổi secret sẽ đăng xuất mọi access token hiện tại.'),
    v('JWT_ACCESS_EXPIRES_IN','Thời gian sống access token.','internal','15m','Tự đặt. Demo nên 15m; không cần lấy từ website nào.','Sau thời gian này API buộc client dùng refresh token để lấy access token mới.','sign(payload, { expiresIn: config.get("JWT_ACCESS_EXPIRES_IN") });','Access token quá dài làm tăng thời gian hữu dụng nếu bị đánh cắp.'),
    v('JWT_REFRESH_SECRET','Khóa ký refresh token dài hạn.','generated','<different-random-64-bytes>','Sinh riêng, theo cùng cách JWT_ACCESS_SECRET.','Chỉ endpoint refresh dùng để xác minh phiên dài hạn và phát access token mới.','verify(refreshToken, { secret: refreshSecret });','Phải lưu hash/rotation metadata của refresh token để có thể thu hồi phiên.'),
    v('JWT_REFRESH_EXPIRES_IN','Thời gian sống phiên đăng nhập.','internal','30d','Tự đặt theo chính sách sản phẩm.','Quyết định người dùng được duy trì đăng nhập bao lâu nếu vẫn có refresh token hợp lệ.','sign(payload, { expiresIn: "30d" });','Càng dài càng cần refresh-token rotation và khả năng revoke.'),
    v('APP_ENCRYPTION_KEY','Khóa mã hóa dữ liệu ứng dụng nhạy cảm.','generated','<32-byte-key>','Sinh bằng CSPRNG; nếu thuật toán yêu cầu đúng 32 byte thì validate độ dài sau decode.','EncryptionService dùng để mã hóa dữ liệu cần giải mã lại. Không dùng khóa này để hash mật khẩu.','createCipheriv("aes-256-gcm", key, iv);','Mất khóa có thể mất khả năng giải mã dữ liệu; phải backup trong secret manager.'),
    v('BCRYPT_SALT_ROUNDS','Chi phí hash mật khẩu.','internal','12','Tự chọn sau khi đo hiệu năng; 10–12 phù hợp demo thông thường.','bcrypt dùng số vòng này khi tạo hash. Giá trị cao hơn chậm hơn và chống brute force tốt hơn.','await bcrypt.hash(password, Number(saltRounds));','Đây không phải secret. Không mã hóa mật khẩu bằng AES; phải hash một chiều.'),
    v('COOKIE_SECURE','Chỉ gửi cookie qua HTTPS.','internal','false','Local HTTP đặt false; production HTTPS bắt buộc true.','Khi true browser không gửi refresh cookie qua kết nối HTTP.','res.cookie(name, token, { httpOnly:true, secure:isProd });','Đặt true trên localhost HTTP làm bạn tưởng đăng nhập hỏng vì cookie không được gửi.'),
    v('COOKIE_SAME_SITE','Kiểm soát gửi cookie giữa các site.','internal','lax','Cùng site dùng lax/strict. Nếu frontend và API thực sự cross-site, có thể cần none kèm secure=true.','Giảm rủi ro CSRF bằng cách hạn chế tình huống browser tự động gửi cookie.','sameSite: config.get("COOKIE_SAME_SITE", "lax")','SameSite=None mà Secure=false thường bị browser chặn.')
  ]},
  { id:'mongodb', name:'MongoDB', note:'Chọn local hoặc MongoDB Atlas', vars:[
    v('MONGODB_URI','Chuỗi kết nối tới database chính.','secret','mongodb://localhost:27017/capstone_book','Atlas: tạo Project → Cluster → Database Access tạo database user → Network Access cho IP → Connect → Drivers → copy URI, thay username/password và tên DB. Local: dùng URI container/local.','Mongoose mở connection pool lúc backend start. Repository/model dùng connection này để đọc ghi Users, Books, Orders, Payments…','MongooseModule.forRoot(config.getOrThrow("MONGODB_URI"));','Database user khác tài khoản đăng nhập Atlas. URL-encode ký tự đặc biệt trong password; không mở 0.0.0.0/0 lâu dài.'),
    v('MONGO_ROOT_USERNAME','Tài khoản quản trị MongoDB container local.','secret','root','Tự đặt trong file Docker local. Chỉ container dùng để khởi tạo.','Mongo image tạo root user lần đầu khi volume database còn trống.','MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}','Không dùng root credential cho ứng dụng production.'),
    v('MONGO_ROOT_PASSWORD','Mật khẩu root MongoDB local.','secret','<random-password>','Tự sinh mật khẩu mạnh. Nếu volume đã khởi tạo, đổi ENV đơn thuần không đổi user trong database.','Đi cùng root username để bootstrap Mongo container.','MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}','Không commit file Docker ENV có password thật.')
  ]},
  { id:'payos', name:'PayOS', note:'Credential bên ngoài — thanh toán VietQR/Napas 24/7', vars:[
    v('PAYOS_CLIENT_ID','Định danh kênh thanh toán PayOS.','secret','<from-payos-channel>','Đăng nhập my.payos.vn → xác thực tổ chức/cá nhân → liên kết ngân hàng → Kênh thanh toán → Tạo kênh → màn hình tích hợp → copy Client ID.','SDK gửi Client ID cùng API Key để PayOS nhận biết kênh merchant đang gọi API.','new PayOS({ clientId: config.getOrThrow("PAYOS_CLIENT_ID"), ... });','Dù không phải mật khẩu độc lập, vẫn giữ ở backend cùng bộ credential.'),
    v('PAYOS_API_KEY','Credential cho phép backend gọi PayOS API.','secret','<from-payos-channel>','Cùng màn hình Kênh thanh toán, copy API Key. Nếu nghi bị lộ, tạo/rotate key trong PayOS và cập nhật nơi deploy.','Backend dùng khi tạo, lấy thông tin hoặc hủy payment request. Không dùng trực tiếp ở Next.js/browser.','apiKey: config.getOrThrow("PAYOS_API_KEY")','Lộ key có thể cho phép người khác gọi API bằng kênh của bạn; tuyệt đối không dùng NEXT_PUBLIC_.'),
    v('PAYOS_CHECKSUM_KEY','Khóa tạo và kiểm tra chữ ký HMAC.','secret','<from-payos-channel>','Copy Checksum Key trong thông tin tích hợp của kênh PayOS.','Khi tạo link, SDK ký dữ liệu để PayOS phát hiện bị sửa. Khi nhận webhook, backend dùng cùng key verify signature để biết payload toàn vẹn.','const data = payOS.webhooks.verify(req.body);','Không tự tin payload chỉ vì request gửi đến đúng path. Luôn verify signature trước cập nhật đơn.'),
    v('PAYOS_RETURN_URL','Trang browser quay về sau khi thanh toán.','internal','http://localhost:3000/payment/payos/success','Tự tạo route frontend này. Production thay localhost bằng domain frontend public.','Được gửi khi tạo payment link. PayOS redirect browser về đây để UI hiển thị kết quả và gọi backend kiểm tra trạng thái.','returnUrl: config.getOrThrow("PAYOS_RETURN_URL")','Không cấp quyền chỉ dựa vào query string ở return URL; người dùng có thể tự sửa URL.'),
    v('PAYOS_CANCEL_URL','Trang browser quay về khi khách hủy.','internal','http://localhost:3000/payment/payos/cancel','Tự tạo route frontend. Có thể dùng chung route với return URL nếu code phân biệt trạng thái.','Cho UI biết khách rời checkout/hủy. Backend có thể kiểm tra rồi hủy reservation phù hợp.','cancelUrl: config.getOrThrow("PAYOS_CANCEL_URL")','Browser quay về cancel không luôn đồng nghĩa giao dịch chắc chắn chưa trả; nên đối soát.'),
    v('PAYOS_WEBHOOK_URL','Endpoint HTTPS để PayOS báo giao dịch cho backend.','internal','https://api.example.com/api/v1/payments/payos/webhook','Production: dùng domain backend. Local: chạy cloudflared tunnel --url http://localhost:4000, lấy URL HTTPS rồi nối path webhook; sau đó xác nhận webhook trong kênh PayOS/API confirm-webhook.','PayOS gọi server-to-server, backend verify chữ ký, đối chiếu order/amount và hoàn tất quyền mua. Đây là nguồn cập nhật chính.','@Post("payos/webhook") async webhook(@Body() body) { return paymentService.handle(body); }','URL phải public HTTPS, trả 2xx nhanh, xử lý idempotent và chấp nhận webhook mẫu khi đăng ký.'),
    v('PAYOS_PAYMENT_EXPIRES_MINUTES','Thời gian khách được phép thanh toán link.','internal','15','Tự đặt theo nghiệp vụ; code đổi phút thành Unix timestamp expiredAt.','Sau hạn, job/logic hủy payment pending và giải phóng tồn kho đã giữ.','expiredAt: Math.floor(Date.now()/1000) + minutes*60','Không dùng thời gian browser; backend là nguồn thời gian tin cậy.')
  ]},
  { id:'minio', name:'MinIO & file Ebook', note:'Object storage tương thích S3', vars:[
    v('MINIO_ENDPOINT','Hostname của MinIO API.','internal','localhost','Local trực tiếp dùng localhost; từ backend container dùng tên service Docker như minio; production dùng hostname storage.','MinIO client ghép endpoint + port + SSL để upload ảnh/PDF và tạo signed URL.','new Client({ endPoint, port, useSSL, accessKey, secretKey });','Không điền http:// vào endPoint nếu SDK yêu cầu hostname riêng.'),
    v('MINIO_PORT','Cổng S3 API, không phải Console.','internal','9000','Mặc định MinIO API là 9000; Console thường là 9001. Kiểm tra output khi server start/Docker mapping.','SDK kết nối API upload/download qua cổng này.','port: Number(config.get("MINIO_PORT", 9000))','Nhầm 9001 sẽ kết nối vào giao diện quản trị và SDK thất bại.'),
    v('MINIO_USE_SSL','Bật HTTPS khi kết nối MinIO.','internal','false','Local HTTP là false. Production có TLS/reverse proxy thì true.','Điều khiển protocol SDK dùng khi tạo request tới object storage.','useSSL: config.get("MINIO_USE_SSL") === "true"','Chuỗi "false" trong JavaScript vẫn truthy nếu ép Boolean sai; phải parse rõ ràng.'),
    v('MINIO_ACCESS_KEY','Tên credential của tài khoản ứng dụng MinIO.','secret','capstone-app','Local có thể tạo bằng MinIO Console hoặc lệnh mc admin user add. Production tạo service account/user quyền tối thiểu.','SDK gửi access key để MinIO xác định principal và policy được phép trên bucket.','accessKey: config.getOrThrow("MINIO_ACCESS_KEY")','Không nên dùng MINIO_ROOT_USER cho app production.'),
    v('MINIO_SECRET_KEY','Mật khẩu đi cùng access key ứng dụng.','secret','<random-password>','Nhận/tự đặt khi tạo MinIO user/service account; lưu ngay vì một số giao diện chỉ hiển thị một lần.','SDK ký request S3. MinIO từ chối nếu key sai hoặc policy thiếu quyền.','secretKey: config.getOrThrow("MINIO_SECRET_KEY")','Lộ key phải rotate; không đưa signed credential vào frontend.'),
    v('MINIO_ROOT_USER / MINIO_ROOT_PASSWORD','Tài khoản quản trị MinIO server local.','secret','<docker-only>','Tự đặt trước lần đầu chạy container bằng ENV của MinIO server.','Container dùng để bootstrap root. Sau đó dùng root tạo bucket và app user quyền tối thiểu.','MINIO_ROOT_USER=${MINIO_ROOT_USER}','Không dùng giá trị mặc định minioadmin/minioadmin; không dùng root trong NestJS.'),
    v('MINIO_EBOOKS_BUCKET','Tên bucket chứa PDF Ebook riêng tư.','internal','ebooks','Tự đặt; script bootstrap tạo bucket nếu chưa tồn tại.','Upload PDF vào bucket private. Khi user có ReadingRight, backend sinh signed URL ngắn hạn.','await ensureBucket(config.get("MINIO_EBOOKS_BUCKET"));','Không đặt bucket Ebook public.'),
    v('MINIO_SIGNED_URL_EXPIRES_IN','Số giây signed URL còn hiệu lực.','internal','300','Tự đặt; 300 giây là 5 phút cho demo.','Giới hạn thời gian URL đọc file hoạt động; hết hạn frontend xin URL mới nếu quyền vẫn hợp lệ.','presignedGetObject(bucket, key, Number(ttl))','Signed URL không thay DRM; người có quyền vẫn có thể ghi lại nội dung.')
  ]},
  { id:'mail', name:'Email SMTP', note:'Xác minh email và đặt lại mật khẩu', vars:[
    v('SMTP_HOST','Máy chủ nhận kết nối gửi mail.','internal','smtp.gmail.com','Lấy từ tài liệu nhà cung cấp email. Gmail dùng smtp.gmail.com; dịch vụ khác có hostname riêng.','Mailer/Nodemailer mở kết nối SMTP tới host này.','createTransport({ host, port, secure, auth });','Không đoán host dựa trên domain email doanh nghiệp.'),
    v('SMTP_PORT / SMTP_SECURE','Cổng và chế độ TLS của SMTP.','internal','587 / false','Lấy từ provider. Thường 587 dùng STARTTLS với secure=false; 465 dùng TLS ngay với secure=true.','Quyết định cách backend thiết lập kết nối mã hóa tới mail server.','port: 587, secure: false','secure=false ở cổng 587 không có nghĩa là email truyền plaintext; STARTTLS nâng cấp kết nối.'),
    v('SMTP_USER','Tài khoản xác thực SMTP.','secret','your-account@gmail.com','Với Gmail thường là địa chỉ Gmail đầy đủ; provider khác cung cấp SMTP username riêng.','Nodemailer dùng với SMTP_PASSWORD để đăng nhập máy chủ gửi mail.','auth: { user: config.getOrThrow("SMTP_USER"), pass: ... }','Có provider dùng username khác MAIL_FROM_ADDRESS.'),
    v('SMTP_PASSWORD','Mật khẩu ứng dụng SMTP.','secret','<16-digit-app-password>','Gmail: bật xác minh 2 bước → Google Account → Security → App passwords → tạo mật khẩu cho ứng dụng. Dùng mã 16 ký tự, không dùng mật khẩu Gmail chính.','Backend dùng duy nhất lúc xác thực SMTP khi gửi email verify/reset.','pass: config.getOrThrow("SMTP_PASSWORD")','App Password có thể bị thu hồi khi đổi mật khẩu Google; workspace admin có thể vô hiệu hóa tính năng.'),
    v('MAIL_FROM_NAME / MAIL_FROM_ADDRESS','Tên và địa chỉ người gửi hiển thị.','internal','CapstoneBook / no-reply@example.com','Chọn địa chỉ đã được provider cho phép/verify. Gmail thường phải trùng hoặc là alias hợp lệ.','Được đặt vào header From của email.','from: `"${fromName}" <${fromAddress}>`','Giả mạo From chưa xác minh dễ bị từ chối hoặc vào spam.'),
    v('MAIL_VERIFY_URL','Trang frontend xử lý token xác minh email.','internal','http://localhost:3000/verify-email','Tự tạo route frontend; production dùng domain thật.','Backend ghép token một lần vào URL rồi gửi email; frontend nhận token và gọi API verify.','const url = `${verifyUrl}?token=${token}`;','Token phải ngắn hạn, dùng một lần và nên lưu hash trong database.')
  ]},
  { id:'ai', name:'AI Chatbot', note:'Chọn đúng một provider hoặc tắt', vars:[
    v('AI_PROVIDER','Chọn adapter AI được backend sử dụng.','internal','openai','Tự đặt openai, gemini hoặc disabled theo provider bạn đã cấu hình.','AIService chọn implementation tương ứng, giúp đổi nhà cung cấp mà controller không thay đổi.','const provider = config.get("AI_PROVIDER", "disabled");','Validate có API key tương ứng khi provider không phải disabled.'),
    v('OPENAI_API_KEY','Secret xác thực OpenAI API.','secret','sk-...','Đăng nhập platform.openai.com → API keys → tạo project key → copy và lưu ngay. Thiết lập billing/budget theo nhu cầu.','Chỉ backend gửi key trong request tới OpenAI. Chatbot controller áp rate limit, lọc quyền và không chuyển key cho browser.','const client = new OpenAI({ apiKey: config.getOrThrow("OPENAI_API_KEY") });','ChatGPT Plus không đồng nghĩa có API credit. Không commit hoặc dùng NEXT_PUBLIC_OPENAI_API_KEY.'),
    v('OPENAI_MODEL','Model ID mà chatbot gọi.','internal','<configured-model-id>','Chọn từ danh sách model hiện có trong tài khoản/tài liệu OpenAI; giữ thành ENV để đổi mà không sửa code.','Được truyền vào request tạo response; ảnh hưởng chất lượng, tốc độ và chi phí.','client.responses.create({ model: config.getOrThrow("OPENAI_MODEL"), input });','Không hardcode model ở nhiều service; validate model cho phép và đặt giới hạn output.'),
    v('GEMINI_API_KEY','Secret xác thực Gemini API nếu dùng Google.','secret','<from-google-ai-studio>','Google AI Studio → API Keys → chọn/import project → Create API key. Dùng key được giới hạn cho Gemini API; lưu khi tạo.','Gemini adapter đọc key ở backend để gọi API. Không cần biến này nếu AI_PROVIDER=openai.','new GoogleGenAI({ apiKey: config.getOrThrow("GEMINI_API_KEY") });','Không đặt ở frontend; rotate ngay nếu key xuất hiện trong Git/log.'),
    v('GEMINI_MODEL','Model ID cho Gemini adapter.','internal','<configured-model-id>','Chọn model đang được tài khoản hỗ trợ từ tài liệu Google AI Studio.','Adapter truyền model khi tạo nội dung. Có thể đổi model độc lập với code.','ai.models.generateContent({ model, contents });','Model ID và khả dụng có thể thay đổi; không coi giá trị ví dụ là vĩnh viễn.')
  ]},
  { id:'frontend', name:'Frontend Next.js', note:'Chỉ các biến thực sự an toàn để lộ', vars:[
    v('NEXT_PUBLIC_APP_URL','URL public của chính frontend.','public','http://localhost:3000','Local tự đặt; production dùng domain website.','Next.js đóng gói biến NEXT_PUBLIC_ vào JavaScript trình duyệt và dùng cho canonical URL/share link.','const appUrl = process.env.NEXT_PUBLIC_APP_URL;','Mọi người dùng có thể xem biến này trong bundle.'),
    v('NEXT_PUBLIC_API_URL','Base URL public để browser gọi backend.','public','http://localhost:4000/api/v1','Lấy từ URL API sau khi backend chạy/deploy.','API client ghép biến này với /auth, /books, /orders… để gửi fetch/axios.','fetch(`${process.env.NEXT_PUBLIC_API_URL}/books`)','Không đặt secret, database URI hoặc credential vào biến NEXT_PUBLIC_.'),
    v('NEXT_PUBLIC_PAYOS_ENABLED','Hiển thị tùy chọn PayOS trên giao diện.','public','true','Tự đặt true/false. Backend vẫn phải kiểm tra PAYOS_ENABLED riêng.','Frontend dùng feature flag để ẩn/hiện nút. Đây không phải kiểm soát bảo mật.','const enabled = process.env.NEXT_PUBLIC_PAYOS_ENABLED === "true";','Người dùng có thể sửa frontend; backend không được tin flag này.')
  ]},
  { id:'ops', name:'Vận hành & giới hạn', note:'Tự đặt theo tài nguyên hệ thống', vars:[
    v('THROTTLE_TTL_MS / THROTTLE_LIMIT','Cửa sổ và số request tối đa.','internal','60000 / 100','Tự chọn rồi điều chỉnh theo quan sát. Auth và webhook nên có chính sách phù hợp riêng.','Rate limiter đếm request theo IP/user trong TTL và trả 429 khi vượt giới hạn.','ThrottlerModule.forRoot([{ ttl: 60000, limit: 100 }]);','Không rate-limit webhook quá chặt khiến PayOS retry liên tục; cân nhắc proxy IP.'),
    v('LOG_LEVEL','Mức chi tiết log.','internal','debug','Local dùng debug; production thường info/warn.','Logger loại bỏ message thấp hơn mức cấu hình.','logger.level = config.get("LOG_LEVEL", "info");','Không log password, token, API key, full webhook secret hoặc dữ liệu cá nhân.'),
    v('SENTRY_DSN','Địa chỉ gửi lỗi tới Sentry, tùy chọn.','secret','<optional>','Tạo project trong Sentry → Project Settings → Client Keys (DSN) → copy DSN. Bỏ trống để tắt.','SDK gửi exception và context đã lọc tới project giám sát.','if (dsn) Sentry.init({ dsn, environment: nodeEnv });','DSN không mạnh như API key nhưng vẫn không nên lạm dụng; scrub PII và token.'),
    v('SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD','Tài khoản admin bootstrap lần đầu.','secret','admin@example.com / <temporary-password>','Tự đặt credential tạm thời trước khi chạy seed. Sau khi tạo admin và đổi mật khẩu, xóa khỏi môi trường production.','Seed script kiểm tra admin chưa tồn tại, hash password rồi tạo user role ADMIN.','await seedAdmin({ email, passwordHash: await hash(password) });','Không chạy seed tạo lại mỗi lần start; không để mật khẩu mặc định lâu dài.')
  ]}
];

function v(name,purpose,type,sample,source,flow,code,warning){return{name,purpose,type,sample,source,flow,code,warning}}
const typeLabels={public:'Public',internal:'Internal',secret:'Secret',generated:'Tự sinh'};
const navItems=[['overview','Tổng quan'],['concepts','ENV là gì?'],['runtime','Luồng nạp ENV'],['catalog','Danh mục biến'],['payos-flow','Luồng PayOS'],['files','Tổ chức file'],['checklist','Checklist'],['sources','Nguồn chính thức']];
const nav=document.querySelector('#nav'); nav.innerHTML=navItems.map(([id,n])=>`<a href="#${id}">${n}</a>`).join('');
const filters=document.querySelector('#filters'); filters.innerHTML=`<button class="filter active" data-group="all">Tất cả</button>`+groups.map(g=>`<button class="filter" data-group="${g.id}">${g.name}</button>`).join('');
const total=groups.reduce((n,g)=>n+g.vars.length,0); document.querySelector('#envCount').textContent=total;

function render(){
  const query=document.querySelector('#search').value.trim().toLowerCase();
  const selected=document.querySelector('.filter.active').dataset.group;
  let count=0;
  const html=groups.map(g=>{
    if(selected!=='all'&&selected!==g.id)return '';
    const vars=g.vars.filter(x=>`${x.name} ${x.purpose} ${x.source} ${x.flow}`.toLowerCase().includes(query));
    count+=vars.length;if(!vars.length)return '';
    return `<div class="group" data-group="${g.id}"><div class="group-title"><h3>${g.name}</h3><p>${g.note}</p></div>${vars.map(card).join('')}</div>`;
  }).join('');
  document.querySelector('#envGroups').innerHTML=html;
  document.querySelector('#resultCount').textContent=`Hiển thị ${count}/${total} biến`;
  document.querySelector('#emptyState').hidden=count!==0;
}
function card(x){return `<article class="env-card"><button class="env-summary" aria-expanded="false"><span class="env-name">${x.name}</span><span class="env-purpose">${x.purpose}</span><span class="badges"><span class="badge ${x.type}">${typeLabels[x.type]}</span></span></button><div class="env-detail"><div class="detail-grid"><div class="detail-block"><h4>Lấy ở đâu / tạo thế nào</h4><p>${x.source}</p><div class="sample"><span>${escapeHtml(x.name+'='+x.sample)}</span><button data-copy-text="${escapeAttr(x.name+'='+x.sample)}">Copy</button></div></div><div class="detail-block"><h4>Tác dụng & luồng xử lý</h4><p>${x.flow}</p></div><div class="detail-block"><h4>Cách đọc trong code</h4><div class="env-code">${escapeHtml(x.code)}</div></div><div class="detail-block"><h4>Lưu ý / lỗi thường gặp</h4><p>${x.warning}</p></div></div></div></article>`}
function escapeHtml(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function escapeAttr(s){return escapeHtml(s).replace(/"/g,'&quot;')}
render();

document.addEventListener('click',e=>{
  const summary=e.target.closest('.env-summary');if(summary){const card=summary.closest('.env-card');card.classList.toggle('open');summary.setAttribute('aria-expanded',card.classList.contains('open'));}
  const filter=e.target.closest('.filter');if(filter){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));filter.classList.add('active');render();}
  const copy=e.target.closest('[data-copy],[data-copy-text]');if(copy){e.stopPropagation();const text=copy.dataset.copyText||document.querySelector(copy.dataset.copy).innerText;navigator.clipboard.writeText(text).then(showToast);}
});
document.querySelector('#search').addEventListener('input',render);
document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();document.querySelector('#search').focus();}});
function showToast(){const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}

const checklist=['Tạo file .env.example không chứa secret','Thêm .env và .env.* vào .gitignore','Sinh riêng JWT access secret và refresh secret','Chuẩn bị MongoDB URI, database user và IP allowlist','Tạo kênh PayOS, lưu Client ID/API Key/Checksum Key','Tạo route return, cancel và webhook PayOS','Chuẩn bị HTTPS public cho webhook','Tạo MinIO app user quyền tối thiểu và bucket private','Tạo SMTP App Password hoặc credential provider','Chọn một AI provider hoặc đặt AI_PROVIDER=disabled','Validate toàn bộ ENV ngay khi backend khởi động','Thiết lập secret trong nền tảng deploy, không copy vào source','Kiểm thử webhook trùng lặp không cấp quyền hai lần','Rotate ngay mọi key từng xuất hiện trong Git hoặc ảnh chụp'];
const box=document.querySelector('#checklistItems');box.innerHTML=checklist.map((x,i)=>`<label class="check-item"><input type="checkbox" data-check="${i}"><span>${x}</span></label>`).join('');
document.querySelectorAll('[data-check]').forEach(el=>{el.checked=localStorage.getItem('env-check-'+el.dataset.check)==='1';el.addEventListener('change',()=>localStorage.setItem('env-check-'+el.dataset.check,el.checked?'1':'0'))});
document.querySelector('#resetChecklist').addEventListener('click',()=>{document.querySelectorAll('[data-check]').forEach(el=>{el.checked=false;localStorage.removeItem('env-check-'+el.dataset.check)})});
const themeToggle=document.querySelector('#themeToggle');const saved=localStorage.getItem('env-theme');if(saved)document.documentElement.dataset.theme=saved;themeToggle.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('env-theme',next)});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id))}}),{rootMargin:'-20% 0px -70%'});navItems.forEach(([id])=>observer.observe(document.getElementById(id)));
