const step=(title,ui,api,data)=>({title,ui,api,data});
const flows=[
['account','Khám phá & đăng nhập','Guest → User đã xác thực','GUEST / USER','low',[step('Khám phá','Tìm kiếm, lọc và xem danh sách.','GET /books','Read only'),step('Chi tiết','Giá, định dạng, tồn kho, Premium.','GET /books/:slug','Read only'),step('Đăng ký','Validate email và mật khẩu.','POST /auth/register','UNVERIFIED'),step('Xác minh','Token email dùng một lần.','POST /auth/verify','ACTIVE'),step('Đăng nhập','Access token + refresh cookie.','POST /auth/login','SESSION')],'MONGODB_URI · JWT_* · SMTP_*','Quay về trang trước hoặc thư viện','Lỗi tại field, giữ dữ liệu đã nhập'],
['ebook','Mua Ebook qua PayOS','Checkout số → quyền đọc vĩnh viễn','USER','high',[step('Tạo đơn','Backend tự tính lại giá.','POST /orders','Order: PENDING'),step('Payment link','Ký dữ liệu và gọi PayOS.','POST /payments/payos','Payment: PENDING'),step('VietQR','Redirect checkoutUrl.','PayOS UI','WAITING'),step('Webhook','Verify chữ ký và amount.','POST /payos/webhook','Payment: PAID'),step('Cấp quyền','Transaction tạo ReadingRight.','PaymentService','Right: ACTIVE'),step('Đọc','Signed URL MinIO 5 phút.','GET /read-url','Reading log')],'PAYOS_* · MINIO_* · MONGODB_URI','Success page polling rồi hiện “Đọc ngay”','Không cấp quyền từ returnUrl; giữ đơn để retry'],
['premium','Đăng ký Premium','Thanh toán → quyền có thời hạn','USER','high',[step('Chọn gói','So sánh quyền lợi và chu kỳ.','GET /premium/plans','Read only'),step('Checkout','Tạo subscription chờ trả tiền.','POST /subscriptions/checkout','PENDING'),step('PayOS','Quét QR và webhook.','POST /payments/payos','Payment: PAID'),step('Kích hoạt','Backend tính startAt/endAt.','SubscriptionService','ACTIVE'),step('Truy cập','Guard kiểm tra hạn và danh mục.','GET /read-url','AUTHORIZED')],'PAYOS_* · JWT_* · MONGODB_URI','Badge Premium và ngày hết hạn rõ ràng','Không cộng thời hạn trước webhook'],
['physical','Sách giấy — PayOS','Giữ kho → trả trước → giao hàng','USER / STAFF','high',[step('Checkout','Địa chỉ và số lượng.','POST /orders','PENDING'),step('Giữ kho','Atomic reserve 15 phút.','InventoryService','RESERVED'),step('Trả tiền','PayOS link đúng amount.','POST /payments/payos','PENDING'),step('Xác nhận','Webhook chốt đơn.','POST /payos/webhook','CONFIRMED'),step('Giao hàng','Đóng gói và tracking.','PATCH /admin/orders','SHIPPING'),step('Hoàn tất','Khách nhận hàng.','Delivery update','DELIVERED')],'PAYOS_* · INVENTORY_RESERVATION_MINUTES','Timeline + mã vận đơn','Hết hạn → release tồn kho'],
['physical','Sách giấy — COD','Đặt hàng → giao → thu tiền','USER / STAFF','medium',[step('Đặt hàng','Chọn COD, xác nhận địa chỉ.','POST /orders','PENDING'),step('Xác nhận','Staff kiểm tra đơn.','PATCH /admin/orders','CONFIRMED'),step('Xuất kho','Transaction trừ kho.','InventoryService','COMMITTED'),step('Giao hàng','Đơn vị giao thu hộ.','Carrier/Admin','SHIPPING'),step('Hoàn tất','Giao thành công ghi nhận COD.','Delivery update','DELIVERED')],'COD_ENABLED · MONGODB_URI · SMTP_*','Timeline và hướng dẫn nhận hàng','Giao thất bại → RETURNING → hoàn kho'],
['return','Đổi trả & hoàn tiền','Yêu cầu → kiểm nhận → hoàn','USER / ADMIN','high',[step('Yêu cầu','Lý do và ảnh bằng chứng.','POST /returns','REQUESTED'),step('Thẩm định','Kiểm tra cửa sổ đổi trả.','PATCH /admin/returns','APPROVED'),step('Nhận hàng','Kho kiểm tra thực tế.','Warehouse update','RECEIVED'),step('Hoàn tiền','Tạo tác vụ đối soát.','RefundService','PROCESSING'),step('Kết thúc','Cập nhật kho và audit.','Transaction','CLOSED')],'MINIO_* · MONGODB_URI · SMTP_*','Hiện timeline và số tiền hoàn','Nêu lý do từ chối và kênh hỗ trợ'],
['reader','Đọc Ebook an toàn','Quyền → signed URL → viewer','USER','medium',[step('Thư viện','Liệt kê sách mua và Premium.','GET /library','Rights query'),step('Kiểm tra','Mua đứt hoặc Premium còn hạn.','RightsGuard','ALLOW / 403'),step('Ký URL','Đúng bucket và object key.','GET /read-url','URL 5 MIN'),step('Đọc','Viewer không nhận storage secret.','MinIO signed GET','SESSION'),step('Gia hạn','Re-check quyền khi URL hết hạn.','GET /read-url','NEW URL')],'MINIO_* · JWT_* · ALLOW_EBOOK_DOWNLOAD','Khôi phục trang đọc gần nhất','403 giải thích lý do và CTA phù hợp'],
['admin','Vận hành Admin','RBAC → thao tác → audit','STAFF / ADMIN','medium',[step('Đăng nhập','Role lấy từ server.','POST /auth/login','ADMIN SESSION'),step('Dashboard','KPI và cảnh báo ngoại lệ.','GET /admin/dashboard','Read only'),step('Thao tác','Endpoint kiểm tra RBAC.','PATCH /admin/...','DOMAIN UPDATE'),step('Audit','Lưu ai, lúc nào, trước/sau.','AuditInterceptor','LOG CREATED'),step('Thông báo','Email/in-app chạy qua queue.','NotificationService','QUEUED')],'JWT_* · MONGODB_URI · SMTP_* · LOG_LEVEL','Toast + dữ liệu mới + audit ref','Rollback và thông báo có thể hành động'],
['ai','AI Chatbot hỗ trợ','Câu hỏi → kiểm soát → gợi ý','USER','low',[step('Nhập hỏi','Giới hạn độ dài và rate.','POST /ai/chat','ACCEPTED'),step('Ngữ cảnh','Sách hiện tại, không có secret.','AIService','PROMPT'),step('Provider','OpenAI hoặc Gemini adapter.','Provider API','GENERATED'),step('Kiểm soát','Không tự mua hoặc thanh toán.','Policy layer','SAFE'),step('Xác nhận','User tự bấm CTA quan trọng.','Frontend','CONSENT')],'AI_PROVIDER · OPENAI_* / GEMINI_*','Trả lời và link sách liên quan','Fallback tìm kiếm thường']
];
const cats={all:'Tất cả',account:'Tài khoản',ebook:'Ebook',premium:'Premium',physical:'Sách giấy',return:'Đổi trả',reader:'Trình đọc',admin:'Admin',ai:'AI'};
const filters=document.querySelector('#filters');filters.innerHTML=Object.entries(cats).map(([k,v],i)=>`<button class="filter ${i?'':'active'}" data-cat="${k}">${v}</button>`).join('');
function renderFlows(){const cat=document.querySelector('.filter.active').dataset.cat;const rows=flows.filter(x=>cat==='all'||x[0]===cat);document.querySelector('#flowList').innerHTML=rows.map((f,i)=>`<article class="flow-card"><button class="flow-head" aria-expanded="false"><code>${String(i+1).padStart(2,'0')}</code><span class="flow-title"><b>${f[1]}</b><span>${f[2]}</span></span><span class="pill">${f[3]}</span><span class="pill ${f[4]}">${f[4].toUpperCase()} RISK</span></button><div class="flow-body"><div class="track">${f[5].map((x,j)=>`<div class="step"><span>${j+1}</span><h4>${x.title}</h4><p>${x.ui}</p><dl><dt>API / SYSTEM</dt><dd>${x.api}</dd><dt>DATA STATE</dt><dd>${x.data}</dd></dl></div>`).join('')}</div><div class="flow-meta"><div><b>ENV DEPENDENCIES</b><span>${f[6]}</span></div><div><b>SUCCESS UX</b><span>${f[7]}</span></div><div><b>RECOVERY UX</b><span>${f[8]}</span></div></div></div></article>`).join('')};renderFlows();
const machines={payment:[['PENDING','Chờ thanh toán','pending'],['PAID','Webhook verified','success'],['COMPLETED','Đã cấp quyền/đơn','success']],order:[['DRAFT','Giỏ hợp lệ','pending'],['PENDING','Đã tạo đơn','pending'],['CONFIRMED','Đã xác nhận','success'],['SHIPPING','Đang giao','pending'],['DELIVERED','Hoàn tất','success']],rights:[['NONE','Chưa có quyền','failed'],['ACTIVE','Được phép đọc','success'],['REVOKED','Thu hồi quyền','failed']],premium:[['PENDING','Chờ thanh toán','pending'],['ACTIVE','Trong thời hạn','success'],['EXPIRED','Hết thời hạn','failed']]};
function drawMachine(key){document.querySelector('#machine').innerHTML=machines[key].map((n,i)=>`${i?'<div class="arrow">validated</div>':''}<div class="node ${n[2]}"><b>${n[0]}</b><span>${n[1]}</span></div>`).join('')}drawMachine('payment');
const screens=[['Trang chủ','Public','Khám phá sách và giá trị sản phẩm',['loading','content','empty','error'],'Một CTA chính theo ngữ cảnh.'],['Danh sách sách','Public','Tìm, lọc, sort và phân trang',['skeleton','results','no-result','retry'],'Filter phản ánh trên URL.'],['Chi tiết sách','Public/User','Giá, format, tồn kho, quyền',['available','owned','premium','sold-out'],'CTA đổi theo quyền thực tế.'],['Giỏ hàng','User','Sửa lượng và tổng dự kiến',['valid','price-changed','stock-changed','empty'],'Giải thích mọi thay đổi trước checkout.'],['Checkout','User','Địa chỉ, phương thức, tổng cuối',['editing','validating','submitting','failed'],'Khóa nút và chống submit kép.'],['Kết quả PayOS','User','Chờ server xác nhận redirect',['verifying','paid','pending','cancelled'],'Không tin query string.'],['Thư viện','User','Mua đứt và sách Premium',['loading','owned','expired','empty'],'Phân biệt nguồn quyền đọc.'],['PDF Reader','Authorized','Đọc qua signed URL',['loading','reading','expired-url','forbidden'],'Gia hạn URL, giữ trang đọc.'],['Theo dõi đơn','User','Timeline giao và đổi trả',['confirmed','shipping','delivered','returning'],'Không dùng màu làm tín hiệu duy nhất.'],['Admin Dashboard','Staff/Admin','KPI và ngoại lệ',['loading','healthy','warning','partial-error'],'Ưu tiên việc cần xử lý.'],['Thanh toán','Admin','Đối soát, recovery có kiểm soát',['pending','matched','mismatch','recovered'],'Không sửa PAID tùy ý.'],['AI Chatbot','User','Hỏi đáp và gợi ý',['idle','thinking','answer','fallback'],'User xác nhận hành động quan trọng.']];
document.querySelector('#screenGrid').innerHTML=screens.map((x,i)=>`<article class="screen"><header><span>${String(i+1).padStart(2,'0')}</span><span>${x[1]}</span></header><h3>${x[0]}</h3><p>${x[2]}</p><div class="states">${x[3].map(y=>`<i>${y}</i>`).join('')}</div><p class="rule"><b>UX RULE:</b> ${x[4]}</p></article>`).join('');
document.addEventListener('click',e=>{const f=e.target.closest('.filter');if(f){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');renderFlows()}const h=e.target.closest('.flow-head');if(h){const c=h.closest('.flow-card');c.classList.toggle('open');h.setAttribute('aria-expanded',c.classList.contains('open'))}const t=e.target.closest('[data-machine]');if(t){document.querySelectorAll('[data-machine]').forEach(x=>x.classList.remove('active'));t.classList.add('active');drawMachine(t.dataset.machine)}});
const theme=document.querySelector('#theme');const saved=localStorage.getItem('flow-theme');if(saved)document.documentElement.dataset.theme=saved;theme.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('flow-theme',next)});
